TaskManagementSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from task import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")), #new
    path("accounts/", include("django.contrib.auth.urls")), #new
    path("assigned_tasks/", views.AssignedTasksListView.as_view(), name="list_assigned_tasks"), #new
    path("repository/", include("repository.urls")), #new
    path("", include("home.urls")), #new
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

repository/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path("", views.RepositoryListView.as_view(), name="repo_list"),
    path("new/",views.CreateRepositoryView.as_view(), name="repo_new"),
    path("<int:repo_id>_<str:repo_name>/", views.RepositoryDetailView.as_view(), name="repo_detail"),
    path("<int:repo_id>_<str:repo_name>/delete/",views.DeleteRepositoryView.as_view(), name="repo_delete"),
    path("<int:repo_id>_<str:repo_name>/profile_<str:username>/",views.PersonalProfileView.as_view(), name="repo_personal_profile"),
    path("<int:repo_id>_<str:repo_name>/tasks/", include("task.urls")),
    path("<int:repo_id>_<str:repo_name>/roles/", views.RolesListView.as_view(), name="role_list"),
    path("<int:repo_id>_<str:repo_name>/roles/new/", views.CreateRoleView.as_view(), name="role_new"),
    path("<int:repo_id>_<str:repo_name>/roles/<int:role_id>/assign/",views.AssignRoleView.as_view(), name="role_assign"),
    path("<int:repo_id>_<str:repo_name>/roles/<int:role_id>/edit/", views.ModifyRoleView.as_view(), name="role_edit"),
    path("<int:repo_id>_<str:repo_name>/roles/<int:role_id>/delete/", views.DeleteRoleView.as_view(), name="role_delete"),
    path("<int:repo_id>_<str:repo_name>/roles/<int:role_id>_<str:role_name>_<str:username>/remove_assign/",views.RemoveAssignRoleView.as_view(), name="role_remove_assign"),
    path("<int:repo_id>_<str:repo_name>/users/",views.UsersListView.as_view(), name="repo_user_list"),
    path("<int:repo_id>_<str:repo_name>/users/add_user/", views.AddUserView.as_view(), name="repo_user_add"),
    path("<int:repo_id>_<str:repo_name>/users/<str:username>/remove_user/", views.RemoveUserView.as_view(), name="repo_user_remove"),
]

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("new/", views.CreateTaskView.as_view(), name="task_new"),
    path("<int:task_id>/",views.TaskDetailView.as_view(), name="task_detail"),
    path("<int:task_id>/assign/", views.AssignTaskView.as_view(), name="task_assign"),
    path("<int:task_id>/edit/", views.ModifyTaskView.as_view(), name="task_edit"),
    path("<int:task_id>/status/", views.ModifyTaskStatusView.as_view(), name="task_status"),
    path("<int:task_id>/delete/", views.DeleteTaskView.as_view(), name="task_delete"),
    path("<int:task_id>/history/", views.HistoryTaskView.as_view(), name="task_history"),
    path("<int:task_id>_<str:task_title>_<str:username>/remove_assign/",views.RemoveAssignTaskView.as_view(), name="task_remove_assign"),
]

task/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.db.models.signals import pre_save,post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError

class Task(models.Model):
    class Task_status(models.TextChoices):
        NEW = "N", _("New")
        ONGOING = "O", _("Ongoing")
        WAITING = "W", _("Waiting")
        FINISHED = "F", _("Finished")
        
    class Task_priority(models.TextChoices):
        DEFERABLE = "D", _("Deferable")
        MODERATE = "M", _("Moderate")
        URGENT = "U", _("Urgent")

    task_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1,choices=Task_status.choices,default=Task_status.NEW)
    priority = models.CharField(max_length=1,choices=Task_priority.choices,default=Task_priority.DEFERABLE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    repo = models.ForeignKey("repository.Repository",on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'tms_task'
    
    def clean(self):
        if self.pk:
            original_status = Task.objects.values_list('status', flat=True).get(pk=self.pk)
            if original_status == "F":
                raise ValidationError("Cannot modify a finished task.")
            
    def save(self, *args, **kwargs):
        self.full_clean()
        is_new_task = not self.pk  # Check if the task is being created
        original_status = self._get_original_status()

        super().save(*args, **kwargs)

        if is_new_task or ((not is_new_task) and self.status != original_status):
            Task_status_history.objects.create(task=self, status=self.status)


    def _get_original_status(self):
        if self.pk:
            return Task.objects.filter(pk=self.pk).values_list('status', flat=True).first()
        return None
    
    def __str__(self):
        return f"{self.task_id} - {self.title} - {self.repo.name}"

@receiver(pre_save, sender=Task)
def update_last_modified(sender, instance, **kwargs):
    if instance.pk:  # Only update if the task already exists
        original_task = Task.objects.get(pk=instance.pk)
        if original_task.last_modified != instance.last_modified:
            # The last_modified attribute has changed
            repository = instance.repo
            repository.last_modified = instance.last_modified
            repository.save()
            
@receiver(post_save, sender=Task)
def update_repository_last_modified(sender, instance, **kwargs):
    repository = instance.repo
    if repository:
        last_modified_task = Task.objects.filter(repo=repository).order_by('-last_modified').first()
        if last_modified_task:
            repository.last_modified = last_modified_task.last_modified
            repository.save()
        
class Task_assignment(models.Model):
    ass_user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    task = models.ForeignKey("Task",on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'tms_task_assignament'
        constraints = [
            models.UniqueConstraint(
                fields=['ass_user', 'task'], name='unique_un_task_constraint'
            )
        ]
        
    def __str__(self):
        return f"{self.task.task_id} - {self.ass_user.username}"

class Task_status_history(models.Model):
    task = models.ForeignKey("Task", on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=Task.Task_status.choices)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'tms_task_status_history'
        
    def __str__(self):
        return f"{self.task.task_id} - {self.created}"

repository/views.py
from django.http import HttpResponse
from django.http import HttpRequest
from django.views.generic import ListView, DetailView  # new
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .mixins.permissions import RepoRolePermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AddUserForm,AssignRoleForm
from .models import Repository,Repo_role,Repo_user
from task.models import Task,Task_assignment
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse_lazy,reverse

#repository views

class RepositoryListView(LoginRequiredMixin,ListView):
    model = Repository
    template_name = "repository/repository_list.html"
    context_object_name = "repo_list"
    pk_url_kwarg = "repo_id"
    
    def get_queryset(self):
        return Repository.objects.all().filter(repo_id__in = Repo_user.objects.all().filter(rp_user=self.request.user).values("role__repo_id").distinct())
    
class CreateRepositoryView(LoginRequiredMixin,CreateView):
    model = Repository
    fields = ["name"]
    template_name = "repository/repository_new.html"
    context_object_name = "repository"
    pk_url_kwarg = "repo_id"
    
    def get_success_url(self):
        return reverse("repo_detail", kwargs={"repo_id": self.object.repo_id , "repo_name": self.object.name})
    
    def form_valid(self, form):
        user = self.request.user
        form.instance.created_by = user if user else None
        self.object = form.save()
        
        new_superadmin_role = Repo_role(
            role_name="Superadmin",
            can_change_status_if_task_assigned=True,
            can_manage_tasks=True,
            can_manage_users=True,
            can_manage_roles=True,
            can_cancel_repo=True,
            repo=self.object
        )
        new_user_role = Repo_role(
            role_name="User",
            can_change_status_if_task_assigned=True,
            can_manage_tasks=False,
            can_manage_users=False,
            can_manage_roles=False,
            can_cancel_repo=False,
            repo=self.object
        )
        new_superadmin_role.save()
        new_user_role.save()

        new_repo_user = Repo_user(rp_user=user, role=new_superadmin_role)
        new_repo_user.save()
        
        return super(CreateRepositoryView, self).form_valid(form)
    
class RepositoryDetailView(LoginRequiredMixin,DetailView):
    model = Repository
    template_name = "repository/repository_detail.html"
    context_object_name = "repository"
    pk_url_kwarg = "repo_id"
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the tasks
        context["repo_tasks"] = Task.objects.all().filter(repo__repo_id = self.kwargs["repo_id"])
        context["repo_tasks_assignment"] = Task_assignment.objects.all().filter(task__repo__repo_id = self.kwargs["repo_id"])
        context["repo_auth_user_role"] = Repo_user.objects.all().filter(rp_user=self.request.user).filter(role__repo__repo_id = self.kwargs["repo_id"])
        return context
    
class DeleteRepositoryView(LoginRequiredMixin,RepoRolePermissionRequiredMixin,DeleteView):
    model = Repository
    template_name = 'repository/repository_delete.html'
    pk_url_kwarg = "repo_id"
    required_permissions = ["can_cancel_repo"]

    def get_success_url(self):
        return reverse('repo_list')
    
#repo personal profile
class PersonalProfileView(LoginRequiredMixin,DetailView):
    model = User
    template_name = "repository/repository_personal_profile.html"
    pk_url_kwarg = "repo_id"
    
    def get_object(self):
        return User.objects.all().filter(username = self.kwargs["username"])
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the tasks
        context["user_roles"] = Repo_user.objects.all().filter(rp_user__username = self.kwargs["username"]).filter(role__repo__repo_id = self.kwargs["repo_id"])
        context["user_tasks"] = Task_assignment.objects.all().filter(ass_user__username = self.kwargs["username"]).filter(task__repo__repo_id = self.kwargs["repo_id"])
        context["repo_tasks_assignment"] = Task_assignment.objects.all().filter(task__repo__repo_id = self.kwargs["repo_id"])
        context["repo_auth_user_role"] = Repo_user.objects.all().filter(rp_user=self.request.user).filter(role__repo__repo_id = self.kwargs["repo_id"])
        return context
    

#roles views
    
class RolesListView(LoginRequiredMixin,RepoRolePermissionRequiredMixin,ListView):
    model = Repo_role
    template_name = "repository/role/role_list.html"
    context_object_name = "role_list"
    pk_url_kwarg = "repo_id"
    required_permissions=["can_manage_roles"]
    
    def get_queryset(self):
        return Repo_role.objects.all().filter(repo__repo_id = self.kwargs["repo_id"])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["repo"] = Repository.objects.get(repo_id = self.kwargs["repo_id"])
        context["repo_users"] = Repo_user.objects.all().filter(role__repo__repo_id=self.kwargs["repo_id"])
        return context

class CreateRoleView(LoginRequiredMixin,RepoRolePermissionRequiredMixin,CreateView):
    model = Repo_role
    fields = ["role_name",
              "can_change_status_if_task_assigned",
              "can_manage_tasks",
              "can_manage_users",
              "can_manage_roles",
              "can_cancel_repo"]
    template_name = "repository/role/role_new.html"
    context_object_name = "role"
    pk_url_kwarg = "repo_id"
    required_permissions=["can_manage_roles"]
    
    def get_success_url(self):
        return reverse("role_list", kwargs={"repo_id": self.kwargs["repo_id"] , "repo_name": self.kwargs["repo_name"]})
    
    def form_valid(self, form):
        form.instance.repo = Repository.objects.get(repo_id=self.kwargs["repo_id"])
        return super(CreateRoleView, self).form_valid(form)

class ModifyRoleView(RepoRolePermissionRequiredMixin,UpdateView):
    model = Repo_role
    fields = ["role_name",
              "can_change_status_if_task_assigned",
              "can_manage_tasks",
              "can_manage_users",
              "can_manage_roles",
              "can_cancel_repo"]
    template_name = "repository/role/role_edit.html"
    context_object_name = "role"
    pk_url_kwarg = "repo_id"
    required_permissions=["can_manage_roles"]
    
    def get_success_url(self):
        return reverse("role_list", kwargs={"repo_id": self.kwargs["repo_id"] , "repo_name": self.kwargs["repo_name"]})
    
    def get_object(self):
        return Repo_role.objects.get(role_id=self.kwargs["role_id"])

class DeleteRoleView(LoginRequiredMixin,RepoRolePermissionRequiredMixin,DeleteView):
    model = Repo_role
    template_name = "repository/role/role_delete.html"
    context_object_name = "role"
    pk_url_kwarg = "repo_id"
    required_permissions=["can_manage_roles"]
    
    def get_success_url(self):
        return reverse("role_list", kwargs={"repo_id": self.kwargs["repo_id"] , "repo_name": self.kwargs["repo_name"]})
    
    def get_object(self):
        return Repo_role.objects.get(role_id=self.kwargs["role_id"])
    
class AssignRoleView(LoginRequiredMixin,RepoRolePermissionRequiredMixin,CreateView):
    form_class = AssignRoleForm
    template_name = "repository/role/role_assign.html"
    pk_url_kwarg = "repo_id"
    required_permissions=["can_manage_roles"]
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["repo_id"] = self.kwargs["repo_id"]
        kwargs["role_id"] = self.kwargs["role_id"]
        return kwargs
    
    def get_success_url(self):
        return reverse("role_list", kwargs={"repo_id": self.kwargs["repo_id"] , "repo_name": self.kwargs["repo_name"]})
    
    def form_valid(self, form):
        form.instance.role = Repo_role.objects.get(role_id=self.kwargs["role_id"])
        return super(AssignRoleView, self).form_valid(form)

class RemoveAssignRoleView(LoginRequiredMixin,RepoRolePermissionRequiredMixin,DeleteView):
    model = Repo_user
    template_name = "repository/role/role_remove_assign.html"
    pk_url_kwarg = "repo_id"
    required_permissions=["can_manage_roles"]

    def get_success_url(self):
        return reverse("role_list", kwargs={"repo_id": self.kwargs["repo_id"] , "repo_name": self.kwargs["repo_name"]})
    
    def get_object(self):
        return Repo_user.objects.all().filter(rp_user__username=self.kwargs["username"]).get(role__role_id=self.kwargs["role_id"])


#repo_users views

   
class UsersListView(LoginRequiredMixin,RepoRolePermissionRequiredMixin,ListView):
    model = Repo_user
    template_name = "repository/repo_user/repo_user_list.html"
    context_object_name = "repo_user_list"
    pk_url_kwarg = "repo_id"
    required_permissions=["can_manage_users"]
    
    def get_queryset(self):
        return User.objects.all().filter(username__in=Repo_user.objects.all().filter(role__repo__repo_id = self.kwargs["repo_id"]).values_list("rp_user__username", flat=True))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["users_role_list"] = Repo_user.objects.all().filter(role__repo__repo_id = self.kwargs["repo_id"])
        context["repo"] = Repository.objects.get(repo_id = self.kwargs["repo_id"])
        return context

class AddUserView(LoginRequiredMixin,RepoRolePermissionRequiredMixin,CreateView):
    form_class = AddUserForm
    template_name = "repository/repo_user/repo_user_add.html"
    pk_url_kwarg = "repo_id"
    required_permissions=["can_manage_users"]
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

templates/repository/task/task_assign.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row align-items-center justify-content-center">
    <div class="col-6 bg-dark p-5 border">
        <h1 class="text-warning text-uppercase">Assign task</h1>
        <form action="" method="post">{% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success w-100 fw-bold fs-4 mt-5 py-2" type="submit">Save</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/repository/task/task_delete.html
{% extends "base.html" %}

{% block content %}
<div class="row align-items-center justify-content-center">
    <div class="col-6 bg-dark p-5 border">
        <h1 class="text-warning text-uppercase">Delete task</h1>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete <span class="text-warning">{{ task.title }}</span>?</p>
            <button class="btn btn-danger w-100 fw-bold fs-4 mt-5 py-2" type="submit">Delete</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/repository/task/task_detail.html
{% extends "base.html" %}

{% block content %}
<div class="row align-items-center justify-content-center">
  <div class="col-6 bg-dark py-3 px-5 border text-warning">
    <div class="py-2 align-top text-center">
      <h1 class="text-warning text-uppercase">TASK</h1>
    </div>
    <div class="py-2">
        Title: <span class="fw-bold text-white">{{ task.title }}</span>
    </div>
    <div class="py-2">
      Priority: <span class="fw-bold text-white">{{ task.get_priority_display }}</span>
    </div>
    <div class="py-2">
      Status: <span class="fw-bold text-white">{{ task.get_status_display }}</span>
    </div>
    <div class="py-2">
      Description: 
      <div class="text-warning my-2 p-3 bg-black border text-wrap text-break">
          <span class="fw-bold text-white">{{ task.description }}</span>
      </div>
    </div>
    <div class="py-2 align-bottom">Back to <a class="text-white text-decoration-none" href="{% url 'repo_detail' view.kwargs.repo_id view.kwargs.repo_name%}">{{ view.kwargs.repo_name }}</a></div> 
  </div>
</div>
{% endblock content %}

templates/repository/task/task_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row align-items-center justify-content-center">
    <div class="col-6 bg-dark p-5 border">
        <h1 class="text-warning text-uppercase">Edit task</h1>
        <form action="" method="post">{% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-warning w-100 fw-bold fs-4 mt-5 py-2" type="submit">Update</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/repository/task/task_history.html
{% extends "base.html" %}

{% block title %}Task History{% endblock title %}

{% block content %}
<div class="row align-items-center justify-content-center">
    <div class="col-6 bg-dark p-5 border">
        <h1 class="text-warning text-uppercase text-center mb-5">{{ task.title }} Task History</h1>

        {% if history_list %}
        {% for history in history_list %}
        <div class="text-warning mb-3 p-3 bg-black border fs-5">
            Status: <span class="text-white">{{ history.get_status_display }}</span><br>
            Modified: <span class="text-white">{{ history.created }}</span>
        </div>
        {% endfor %}
        {% else %}
        <p>No history available for this task.</p>
        {% endif %}
        <br><br>
        <p class="text-warning">Back to <a class="text-white text-decoration-none" href="{% url 'repo_detail' view.kwargs.repo_id view.kwargs.repo_name%}">{{ view.kwargs.repo_name }}</a></p>
    </div>
</div>
{% endblock content %}

templates/repository/task/task_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row align-items-center justify-content-center">
    <div class="col-6 bg-dark p-5 border">
        <h1 class="text-warning text-uppercase">New task</h1>
        <form action="" method="post">{% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success w-100 fw-bold fs-4 mt-5 py-2" type="submit">Save</button>
        </form>
    </div>
</div>
    
{% endblock content %}

templates/repository/task/task_remove_assign.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row align-items-center justify-content-center">
    <div class="col-6 bg-dark p-5 border">
        <h1 class="text-warning text-uppercase">Remove assign task</h1>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure to remove the assigned task <span class="text-warning">{{ view.kwargs.task_title }}</span> from the user <span class="text-warning">{{ view.kwargs.username }}?</span></p>
            <button class="btn btn-danger w-100 fw-bold fs-4 mt-5 py-2" type="submit">Delete</button>
        </form>
    </div>
</div>
{% endblock content %}