TaskManagementSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from task import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")), #new
    path("accounts/", include("django.contrib.auth.urls")), #new
    path("assigned_tasks/", views.AssignedTasksListView.as_view(), name="list_assigned_tasks"), #new
    path("repository/", include("repository.urls")), #new
    path("", include("home.urls")), #new
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

repository/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import MaxValueValidator
from task.models import Task

class Repository(models.Model):
    repo_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'tms_repository'
        
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        last_modified_task = Task.objects.filter(repo_id=self).order_by('-last_modified').first()
        if last_modified_task:
            self.last_modified = last_modified_task.last_modified
            super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name
        
        
class Repo_role(models.Model):
    role_id = models.AutoField(primary_key=True)
    role_name = models.CharField(max_length=30)
    can_change_status_if_task_assigned = models.BooleanField(default=True)
    can_manage_tasks = models.BooleanField(default=False)
    can_manage_users = models.BooleanField(default=False)
    can_manage_roles = models.BooleanField(default=False)
    can_cancel_repo = models.BooleanField(default=False)
    repo = models.ForeignKey("Repository",on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'tms_repo_role'
    
    def __str__(self):
        return f"{self.role_name} - {self.repo.name}"
        
class Repo_user(models.Model):
    rp_user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    role = models.ForeignKey("Repo_role",on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'tms_repo_user'
        constraints = [
            models.UniqueConstraint(
                fields=['rp_user', 'role'], name='unique_un_role_constraint'
            )
        ]
    
    def __str__(self):
        return f"{self.rp_user.username} - {self.role.role_name}"
        

templates/role/role_list.html
{% extends "base.html" %}

{% block title %}Repository Roles{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
<div class="repository-entry">
    <h2>{{ repo.name }} Roles Manager</h2>
</div>
<div>
    <p>
        <a class="btn btn-primary" href="{% url 'role_new' repo.repo_id repo.name %}" role="button">Create Role</a>
        <a class="btn btn-primary" href="" role="button">Assign Role</a>
    </p>
    <!-- Role List -->
    {% for role in role_list %}
    <div class="card">
        <div class="d-inline-flex card-header align-items-center justify-content-between">
            <div class="text-start">
                <span class="fw-bold"> {{ role.role_name }} </span>
            </div>
        </div>
        <div class="card-body">
            <span class="fw-bold">
                {% if repo_user_list %}
                {% for repo_user in role.repo_users %}
                <p>{{ repo_user.username }}</p>
                {% endfor %} 
                {% endif %}
            </span>
        </div>
        <div class="card-footer text-center text-muted">
            <a class="btn btn-primary" href="{% url 'role_edit' repo.repo_id repo.name role.role_id%}" role="button">Modify Role</a>
            <a class="btn btn-primary" href="{% url 'role_delete' repo.repo_id repo.name role.role_id%}" role="button">Cancel Role</a>
        </div>
    </div>
    <br />
    {% endfor %}
    <p>Back to <a href="{% url 'repository_detail' repo.repo_id repo.name%}">{{ repo.name }}</a></p>
</div>
{% endif %}
{% endblock content %}